### ISSUE TITLE
Unable to load dynamic library '/usr/lib64/php/modules/php_mapscript.so'

### ISSUE THREAD

**Issue by R4z0R7** [bjoernboldt/mapscript-php7#2]
When compiling for php 7, everything seems fine during the compilation and installation process, but I  get:

PHP Warning: PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/php_mapscript.so' - /usr/lib64/php/modules/php_mapscript.so: undefined symbol: mapscript_create_legend in Unknown on line 0

This happens with every php version - from 7.0 to 7.2.3. Can't load the extension properly. Using CentOS 7.

Any ideas how to fix it ?

**Comment by bjoernboldt** [comment]
I fixed an error in legend.c now. Try new version and report results please.

**Comment by R4z0R7** [comment]
Hello,

Thanks, the error regarding mapscript_create_legend is gone now. However, I get another, similar error:

PHP Warning: PHP Startup: Unable to load dynamic library 'php_mapscript' (tried: /usr/lib64/php/modules/php_mapscript (/usr/lib64/php/modules/php_mapscript: cannot open shared object file: No such file or directory), /usr/lib64/php/modules/php_mapscript.so (/usr/lib64/php/modules/php_mapscript.so: undefined symbol: mapscript_create_grid)) in Unknown on line 0

**Comment by bjoernboldt** [comment]
I fixed the error in grid.c too and tried on CentOS 7.4 / PHP 7.2.3 -  php_mapscript.so is loaded and displayed in phpinfo. Had no time to test a real map yet.

**Comment by R4z0R7** [comment]
Thanks again, with the fix in grid.c the extension loads perfectly fine with no errors !
